version: '3'
services:
  azure-vote-back:
    # Chip amd64
    #image: mcr.microsoft.com/oss/bitnami/redis:6.0.8
    # Chip arm64
    image: redis:6.2
    container_name: azure-vote-back
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
        - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: mcr.microsoft.com/azuredocs/azure-vote-front:v1
    container_name: azure-vote-front
    environment:
      REDIS: azure-vote-back
    ports:
        - "8080:80"
